List slider1ImageLists = [
  {'id': 1, 'image': 'assets/images/tip1.png'},
  {'id': 2, 'image': 'assets/images/login.png'},
  {'id': 3, 'image': 'assets/images/otp.png'},
];
List gifSliderImageLists = [
  {'id': 1, 'image': 'assets/images/work.gif'},
  {'id': 2, 'image': 'assets/images/a.gif'},
  {'id': 3, 'image': 'assets/images/rotating_earth.gif'},
];
List audioBookLists = [
  {'audio_book_image': 'assets/images/otp.png'},
  {'audio_book_image': 'assets/images/login.png'},
  {'audio_book_image': 'assets/images/otp.png'},
  {'audio_book_image': 'assets/images/login.png'},
  {'audio_book_image': 'assets/images/otp.png'},
  {'audio_book_image': 'assets/images/otp.png'},
  {'audio_book_image': 'assets/images/otp.png'},
];
List popularMockTestLists = [
  {
    'image': 'assets/images/otp.png',
    "title": "45th BCS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
  {
    'image': 'assets/images/otp.png',
    "title": "45th BCS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
  {
    'image': 'assets/images/otp.png',
    "title": "45th BCS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
  {
    'image': 'assets/images/otp.png',
    "title": "45th BCS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
  {
    'image': 'assets/images/login.png',
    "title": "45th BCS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
  {
    'image': 'assets/images/login.png',
    "title": "45th BCS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
  {
    'image': 'assets/images/login.png',
    "title": "45th BCS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
  {
    'image': 'assets/images/otp.png',
    "title": "45th BCS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
  {
    'image': 'assets/images/otp.png',
    "title": "45th BCS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
];
List govtMockTestLists = [
  {
    'image': 'assets/images/otp.png',
    "title": "45th BCS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
  {
    'image': 'assets/images/otp.png',
    "title": "45th BCS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
  {
    'image': 'assets/images/otp.png',
    "title": "45th BCS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
  {
    'image': 'assets/images/otp.png',
    "title": "45th BCS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
  {
    'image': 'assets/images/login.png',
    "title": "45th BCS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
  {
    'image': 'assets/images/login.png',
    "title": "45th BCS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
  {
    'image': 'assets/images/login.png',
    "title": "45th BCS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
  {
    'image': 'assets/images/otp.png',
    "title": "45th BCS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
  {
    'image': 'assets/images/otp.png',
    "title": "45th BCS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
];
List privateTestLists = [
  {
    'image': 'assets/images/otp.png',
    "title": "IELTS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
  {
    'image': 'assets/images/otp.png',
    "title": "IELTS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
  {
    'image': 'assets/images/otp.png',
    "title": "IELTS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
  {
    'image': 'assets/images/otp.png',
    "title": "IELTS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
  {
    'image': 'assets/images/login.png',
    "title": "IELTS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
  {
    'image': 'assets/images/login.png',
    "title": "IELTS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
  {
    'image': 'assets/images/login.png',
    "title": "IELTS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
  {
    'image': 'assets/images/otp.png',
    "title": "IELTS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
  {
    'image': 'assets/images/otp.png',
    "title": "IELTS Mock Test",
    "examTime": "20 mins",
    "rating": "10",
    "price": "৫৯০",
  },
];

List mcqTestLists = [
  {
    "examType": "Free",
    "title": "45th BCS Mcq Test",
    "examMarks": "100 marks",
    "examTime": "30 mins",
    "examQuestionNumber": "100 questions",
  },
  {
    "examType": "Paid",
    "title": "Tips For Mcq Test",
    "examMarks": "100 marks",
    "examTime": "30 mins",
    "examQuestionNumber": "100 questions",
  },
  {
    "examType": "Free",
    "title": "45th BCS Mock Test",
    "examMarks": "100 marks",
    "examTime": "30 mins",
    "examQuestionNumber": "100 questions",
  },
  {
    "examType": "Free",
    "title": "45th BCS Mcq Test",
    "examMarks": "100 marks",
    "examTime": "30 mins",
    "examQuestionNumber": "100 questions",
  },
  {
    "examType": "Paid",
    "title": "Tips For Mcq Test",
    "examMarks": "100 marks",
    "examTime": "30 mins",
    "examQuestionNumber": "100 questions",
  },
  {
    "examType": "Paid",
    "title": "Tips For Mcq Test",
    "examMarks": "100 marks",
    "examTime": "30 mins",
    "examQuestionNumber": "100 questions",
  },
  {
    "examType": "Free",
    "title": "45th BCS Mcq Test",
    "examMarks": "100 marks",
    "examTime": "30 mins",
    "examQuestionNumber": "100 questions",
  },
  {
    "examType": "Paid",
    "title": "Tips For Mcq Test",
    "examMarks": "100 marks",
    "examTime": "30 mins",
    "examQuestionNumber": "100 questions",
  },
];
